name: pipeline

on:
  push:
    branches: [master]

jobs:
  # --- ÉTAPE 1 : TESTS UNITAIRES ---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Restaurer les dépendances
        run: dotnet restore

      - name: Lancer les tests
        run: dotnet test TestPersonneControllerGetById/TestPersonneControllerGetById.csproj --no-restore

      - name: Notification Teams si échec
        if: failure()
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"text":"❌ Les tests ont échoué sur la branche ${{ github.ref }}"}' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

  # --- ÉTAPE 2 : GÉNÉRATION DE L'ARTIFACT ---
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Restaurer les dépendances
        run: dotnet restore

      - name: Build
        run: dotnet build CarApiClean/CarApiClean.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish CarApiClean/CarApiClean.csproj --no-restore --configuration Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # <-- PASSAGE EN V4 ICI
        with:
          name: app-publish
          path: ./publish

  # --- ÉTAPE 3 : DÉPLOIEMENT SUR AZURE ---
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 # <-- PASSAGE EN V4 ICI
        with:
          name: app-publish
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3 # <-- VERSION RÉCENTE
        with:
          app-name: 'kevapi'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish